AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa Skill

Resources:
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/alexa
      Handler: index.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_TABLE: !Ref TokenTable
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref TokenTable
        - Version: '2012-10-17' # Policy Document
          Statement:
           - Effect: Allow
             Action:
               - iot:Publish
             Resource: !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/lighting/*'

  ResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/response_handler
      Handler: index.lambda_handler
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TokenTable
      Environment:
        Variables:
          TOKEN_TABLE: !Ref TokenTable
      Events:
        IoT:
          Type: IoTRule
          Properties:
            AwsIotSqlVersion: 2016-03-23
            Sql: "SELECT * FROM 'lighting/response'"

  TokenTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: bearer
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      AllowUnauthenticatedIdentities: false
